oh

diff --git a/bin/upd b/bin/upd
--- a/bin/upd
+++ b/bin/upd
@@ -1,7 +1,6 @@
 #!/usr/bin/env sh
 
 upd_pypi3=true
-upd_gentoo_overlays=true
 upd_gentoo_repos=true
 upd_git_repos=true
 
@@ -13,8 +12,7 @@ Usage: upd [OPTIONS]
 Options:
 	-h	displays this message
 	-p	disables pip package updates
-	-l	disables gentoo overlay sync
-	-g	disables gentoo repo sync
+	-g	disables gentoo repos sync
 	-G	disables git repo updating
 
 "
@@ -26,7 +24,6 @@ get_args() {
 		case $OPTS in
 			h ) usage;exit 0 ;;
 			p ) upd_pypi3=false ;;
-			l ) upd_gentoo_overlays=false ;;
 			g ) upd_gentoo_repos=false ;;
 			G ) upd_git_repos=false ;;
 			* ) usage;exit 1;;
@@ -58,24 +55,6 @@ pypi3() {
 	echo "Done."
 }
 
-gentoo_overlays() {
-	if [ "$upd_gentoo_overlays" = false ]
-	then
-		echo "Skipping Gentoo Overlays synchronization..."
-		return 0
-	fi
-
-	if ! command -v layman > /dev/null
-	then
-		echo "layman not found"
-		return 1
-	fi
-
-	echo "Updating Gentoo Overlay Repositories..."
-	sudo layman -S
-	echo "Done."
-}
-
 gentoo_repos() {
 	if [ "$upd_gentoo_repos" = false ]
 	then
@@ -90,7 +69,16 @@ gentoo_repos() {
 	fi
 
 	echo "Updating Gentoo Repository..."
-	sudo emaint sync -a
+	sudo emaint sync -A
+	if ! command -v eix > /dev/null
+	then
+		echo "eix not found"
+	else
+		sudo cp -a /var/cache/eix/portage.eix \
+			/var/cache/eix/previous.eix
+		sudo eix-update
+		sudo eix-remote update
+	fi
 	echo "Done."
 }
 
@@ -126,14 +114,13 @@ main() {
 
 	get_args "$@"
 
-	if [ $upd_gentoo_repos = true ] || [ $upd_gentoo_overlays = true ]
+	if [ $upd_gentoo_repos = true ]
 	then
 		sudo -v
 	fi
 
 	git_repos
 	pypi3
-	gentoo_overlays
 	gentoo_repos
 }
 
