Skeet Yeet

diff --git a/noti/music/music-changed b/noti/music/music-changed
--- a/noti/music/music-changed
+++ b/noti/music/music-changed
@@ -1,27 +1,28 @@
 #!/usr/bin/env sh
 
-# Script to display notifcation when song changes
-# Requires:
-#	libnotify or dunstify
-#	mpd
-#	mpc
-
-app_name="MPD Status"
+app_name="MPD"
 summary="Now Playing"
 
-if command -v dunstify; then
-	while :; do
+if command -v dunstify
+then
+	while true
+	do
 		dunstify -a "${app_name}" \
 			-t 4000 \
 			-r 13596705 \
 			"${summary}" \
 			"$(mpc current --wait)"
 	done
-else
-	while :; do
+elif command -v notify-send
+then
+	while true
+	do
 		notify-send -t 4000 \
 			-a "${app_name}" \
 			"${summary}" \
 			"$(mpc current --wait)"
 	done
+else
+	echo "dunstify or libnotify not found"
+	exit 1
 fi
diff --git a/noti/music/music-info b/noti/music/music-info
--- a/noti/music/music-info
+++ b/noti/music/music-info
@@ -1,65 +1,58 @@
 #!/usr/bin/env sh
 
-# Notification Script to display information about MPD
-# Requires:
-#	libnotify or dunstify
-#	mpc
-#	mpd
+app_name="MPD Info"
 
-app_name="MPD Status"
-
-if ! [ "$(mpc current)" ]; then
-	summary="MPD: Stopped"
-	body="MPD has been stopped"
+if ! [ "$(mpc current)" ]
+then
+	summary="[Stopped]"
 else
-	if mpc status | grep -q paused; then
-		PAUSE="[Paused]"
-	else
-		PAUSE=""
+	if mpc status | grep -q paused
+	then
+		play="[Paused]"
 	fi
 
-	VOL="[$(mpc volume | awk '{print $2}')]"
-
-	if [ "$(mpc crossfade | awk '{print $2}')" -gt 0 ]; then
-		CFADE="x"
-	else
-		CFADE=""
+	if [ "$(mpc crossfade | awk '{print $2}')" -gt 0 ]
+	then
+		fade="x"
 	fi
 
-	if [ "$(mpc status | awk NR==3'{print $4}')" = "on" ]; then
-		RE="r"
-	else
-		RE=""
+	if [ "$(mpc status | awk NR==3'{print $4}')" = "on" ]
+	then
+		re="r"
 	fi
 
-	if [ "$(mpc status | awk NR==3'{print $6}')" = "on" ]; then
-		RAN="z"
-	else
-		RAN=""
+	if [ "$(mpc status | awk NR==3'{print $6}')" = "on" ]
+	then
+		ran="z"
 	fi
 
-	if [ "$(mpc status | awk NR==3'{print $8}')" = "on" ];then
-		SIN="s"
-	else
-		SIN=""
+	if [ "$(mpc status | awk NR==3'{print $8}')" = "on" ]
+	then
+		sin="s"
 	fi
 
-	SONGNUM="[$(mpc listall | wc -l)]"
+	vol="[$(mpc volume | awk '{print $2}')]"
+	time="[$(mpc | awk NR==2'{print $3}')]"
+	num="[$(mpc listall | wc -l)]"
 
-	summary="${SONGNUM} [${RE}${RAN}${SIN}${CFADE}] ${VOL} ${PAUSE}"
+	summary="${num} [${re}${ran}${sin}${fade}] ${vol} ${time} ${play}"
 	body="$(mpc current)"
-
 fi
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
 		"${summary}" \
 		"${body}"
-else
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
 		"${summary}" \
 		"${body}"
+else
+	echo "dunstify or libnotify not found"
+	exit 1
 fi
diff --git a/noti/music/music-stop b/noti/music/music-stop
--- a/noti/music/music-stop
+++ b/noti/music/music-stop
@@ -1,28 +1,27 @@
 #!/usr/bin/env sh
 
-# Script to stop MPD and display a notification
-# Requires:
-#	libnotify or dunstify
-#	mpd
-#	mpc
-
-app_name="MPD Status"
-summary="Stopped"
-body="MPD has been stopped"
+app_name="MPD"
+summary="[Stopped]"
+body=
 
 mpc stop
-
 sleep .01
-if command -v dunstify; then
+
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
 		"${summary}" \
 		"${body}"
-else
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
 		"${summary}" \
 		"${body}"
+else
+	echo "dunstify or libnotify not found"
+	exit 1
 fi
 
diff --git a/noti/music/music-toggle b/noti/music/music-toggle
--- a/noti/music/music-toggle
+++ b/noti/music/music-toggle
@@ -1,30 +1,26 @@
 #!/usr/bin/env sh
 
-# Script to Toggle music and display a notification
-# Requires:
-#	libnotify or dunstify
-#	mpc
-#	mpd
-
-app_name="MPD Status"
-
-if mpc toggle | grep -q paused; then
-	summary="MPD Paused"
-	body="$(mpc current)"
+if mpc toggle | grep -q paused
+then
+	app_name="MPD Paused"
+	summary="$(mpc current)"
 else
-	summary="MPD Playing"
-	body="$(mpc current)"
+	app_name="MPD Playing"
+	summary="$(mpc current)"
 fi
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
-		"${summary}" \
-		"${body}"
-else
+		"${summary}" 
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
-		"${summary}" \
-		"${body}"
+		"${summary}" 
+else
+	echo "dunstify or libnotify not found"
+	exit 1
 fi
diff --git a/noti/music/music-volume-down b/noti/music/music-volume-down
--- a/noti/music/music-volume-down
+++ b/noti/music/music-volume-down
@@ -1,25 +1,22 @@
 #!/usr/bin/env sh
 
-# Script to decrease mpd volume and display a notification
-# Requires:
-#	libnotify or dunstify
-#	mpd
-#	mpc
-
-app_name="MPD Status"
-summary="Volume Down"
+app_name="MPD Volume"
+summary="Decreasing: $(mpc volume | awk '{print $2}')"
 
 mpc volume -2
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
-		"${summary}" \
-		"$(mpc volume | awk '{print $2}')"
-else
+		"${summary}"
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
-		"${summary}" \
-		"$(mpc volume | awk '{print $2}')"
+		"${summary}"
+else
+	echo "dunstify or libnotify not found"
+	exit 1
 fi
