Big

diff --git a/root/home/bin/scr b/root/home/bin/scr
--- a/root/home/bin/scr
+++ b/root/home/bin/scr
@@ -1,153 +1,156 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC1090,SC2154
 
-[[ -z $SCR_CONFIG_DIR ]] && SCR_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/scr"
-# shellcheck source=/home/ye/cfg/scr/config.sh
-. "${SCR_CONFIG_DIR}/config.sh"
+# SC1090 & SC2154
+# The files sourced are user generated files that should contain the needed
+# variables for the script to function correctly. It should be safe to ignore
+# these warnings.
 
-usage() { printf '%s' "usage: ${0##*/} action [options]
+[[ -z $SCR_CFG_DIR ]] && SCR_CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/scr"
+[[ -z $SCR_CACHE_DIR ]] && SCR_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/scr"
+. "$SCR_CFG_DIR/config.sh" || \
+	{ echo "${0##*/}: could not source $SCR_CONFIG_DIR/config.sh"; exit 1; }
 
-actions:
-	aud	audio
-	pic	picture
-	rec	record
-
-options:
-	-a	record desktop audio
-	-c	copy picture to clipboard
-	-f	fullscreen
-	-h	display this message
-	-m	record microphone audio
-
-"
+usage() {
+	printf '%s\n' "usage: ${0##*/} action [options]" \
+	              "\nactions:" \
+	              "  aud - audio" \
+	              "  pic - picture" \
+	              "  rec - record" \
+	              "options:" \
+	              "  -a - record desktop audio" \
+	              "  -c - copy picture to clipboard" \
+	              "  -f - fullscreen" \
+	              "  -h - display this message" \
+	              "  -m - record microphone audio"
 }
 
 case $1 in
-    aud ) action="scr_aud" ;;
-    pic ) action="scr_pic" ;;
-    rec ) action="scr_rec" ;;
-    *help ) usage; exit 0 ;;
-    * ) usage; exit 1 ;;
+	aud   ) action="scr_aud" ;;
+	pic   ) action="scr_pic" ;;
+	rec   ) action="scr_rec" ;;
+	*help ) usage; exit 0 ;;
+	*     ) usage; exit 1 ;;
 esac
 shift
 
 for (( a=1; a<$(( ${#@} + 1 )); a++ ))
 do
-    arg=${!a}
-    [[ ! $arg =~ ^-.* || ${#arg} -lt 2 ]] && continue
-    for (( i=1; i<${#arg}; i++ ))
-    do
-	case ${arg:$i:1} in
-	    a ) desktop_audio=true ;;
-	    c ) copy_clipboard=true ;;
-	    f ) fullscreen=true ;;
-	    h ) usage; exit 0 ;;
-	    m ) microphone=true ;;
-	    * ) printf '%s\n' "${0##*/}: -${arg:$1:1} is an invalid argument"; usage; exit 1 ;;
-	esac
-    done
+	arg=${!a}
+	[[ ! $arg =~ ^-.* || ${#arg} -lt 2 ]] && continue
+	for (( i=1; i<${#arg}; i++ ))
+	do
+		case ${arg:$i:1} in
+			a ) desktop_audio=true ;;
+			c ) copy_clipboard=true ;;
+			f ) fullscreen=true ;;
+			h ) usage; exit 0 ;;
+			m ) microphone=true ;;
+			* ) printf '%s\n' "${0##*/}: -${arg:$1:1}: invalid argument"
+			    usage; exit 1 ;;
+		esac
+	done
 done
 
 die() {
-    printf '%s\n' "${0##*/}: $*"
-    exit 1
+	printf '%s\n' "${0##*/}: $*"
+	exit 1
 }
 
 scr_aud() {
-    [[ ! -d ${scr_aud_dir} ]] && { mkdir -p "${scr_aud_dir}" || die "failed to create directory ${scr_aud_dir}"; }
-    filename="$scr_aud_dir/$aud_filename"
-    mimetype="$aud_mimetype"
-    [[ -z $microphone && -z $desktop_audio ]] && {
-	die "aud: argument -a or -m is required to record audio" "run \`scr help\` for more information"
-    }
-    [[ $microphone = true ]] && { read -ra args <<< "$aud_mic_args"; }
-    [[ $desktop_audio = true ]] && { read -ra args <<< "${args[*]} $aud_desktop_audio_args"; }
-    [[ $microphone = true && $desktop_audio = true ]] && { read -ra args <<< "${args[*]} $aud_multi_audio_args";}
-    echo "${args[@]}"
-    ffmpeg "${args[@]}" "$filename" &> /tmp/scr_aud.log
-    echo "$filename"
+	[[ -d $scr_aud_dir ]] || \
+		{ mkdir -p "$scr_aud_dir" || die "failed to make directory: $scr_aud_dir"; }
+
+	[[ -d $SCR_CACHE_DIR ]] || \
+		{ mkdir -p "$SCR_CACHE_DIR" || \
+		  die "failed to make directory: $SCR_CACHE_DIR"; }
+
+	filename="$scr_aud_dir/$aud_filename"
+
+	[[ -z $microphone && -z $desktop_audio ]] && {
+		die "aud: argument -a or -m is required to record audio" \
+		    "run \`scr help\` for more information about arguments"
+	}
+
+	[[ -n $microphone ]] && { _args="-f pulse -i $aud_source"; }
+	[[ -n $desktop_audio ]] && { _args="$_args -f pulse -i $aud_sink"; }
+	[[ -n $microphone && -n $desktop_audio ]] && \
+		{ _args="$_args -filter_complex amix=inputs=2"; }
+	read -ra args <<< "$_args"
+
+	ffmpeg "${args[@]}" "$filename" &> "$SCR_CACHE_DIR/aud.log"
+	echo "$filename"
 }
 
 scr_pic() {
-    [[ ! -d ${scr_pic_dir} ]] && { mkdir -p "${scr_pic_dir}" || die "failed to create directory ${scr_pic_dir}"; }
-    filename="$scr_pic_dir/$pic_filename"
-    mimetype="$pic_mimetype"
-    [[ $XDG_SESSION_TYPE = wayland ]] && {
-	[[ $fullscreen != true ]] && {
-	    read -ra args <<< "$wl_selection_args"
-	    read -r geometry < <(slurp "${args[@]}")
-	    pic_selection="-g-"
+	[[ -d $scr_pic_dir ]] || \
+		{ mkdir -p "$scr_pic_dir" || die "failed to make directory: $scr_pic_dir"; }
+
+	[[ -d $SCR_CACHE_DIR ]] || \
+		{ mkdir -p "$SCR_CACHE_DIR" || \
+		  die "failed to create directory: $SCR_CACHE_DIR"; }
+
+	filename="$scr_pic_dir/$pic_filename"
+
+	[[ -z $fullscreen ]] && {
+		read -r geom < <(slurp)
+		pic_sel="-g-"
 	}
-	read -ra args <<< "$pic_selection $wl_pic_args"
-	printf '%s' "$geometry" | grim "${args[@]}" "$filename"
-	[[ $copy_clipboard = true ]] && {
-	    read -ra args <<< "$wl_clipboard_args -t $mimetype"
-	    wl-copy "${args[@]}" < "$filename"
-	}
-    }
-    [[ $XDG_SESSION_TYPE != wayland ]] && {
-	[[ $fullscreen != true ]] && {
-	    read -ra args <<< "$X11_selection_args -f '%x %y %w %h'"
-	    read -r X Y W H < <(slop "${args[@]}")
-	    pic_selection="-crop ${W}x${H}+${X}+${Y}"
-	}
-	read -ra args <<< "-window root $pic_selection $X11_pic_args"
-	import "${args[@]}" "$filename"
-	[[ $copy_clipboard = true ]] && {
-	    read -ra args <<< "$X11_clipboard_args -i -t $mimetype"
-	    xclip "${args[@]}" "$filename"
-	}
-    }
-    echo "$filename"
+
+	printf '%s' "$geom" | grim "$pic_sel" "$filename" &> "$SCR_CACHE_DIR/pic.log"
+	[[ -n $copy_clipboard ]] && \
+		{ wl-copy  < "$filename" &> "$SCR_CACHE_DIR/copy.log"; }
+	
+	echo "$filename"
 }
 
 scr_rec() {
-    [[ ! -d ${scr_rec_dir} ]] && { mkdir -p "${scr_rec_dir}" || die "failed to create directory ${scr_pic_dir}"; }
-    filename="$scr_rec_dir/rec_filename"
-    mimetype="$rec_mimetype"
-    [[ $XDG_SESSION_TYPE = wayland ]] && {
-	[[ $fullscreen != true ]] && {
-	    read -ra args <<< "$wl_selection_args"
-	    read -r geometry < <(slurp "${args[@]}")
-	    pic_selection="-g $geometry"
+	[[ -d $scr_rec_dir ]] || \
+		{ mkdir -p "$scr_rec_dir" || die "failed to make directory: $scr_pic_dir"; }
+
+	[[ -d $SCR_CACHE_DIR ]] || \
+		{ mkdir -p "$SCR_CACHE_DIR" || \
+		  die "failed to make directory: $SCR_CACHE_DIR"; }
+
+	filename="$scr_rec_dir/$rec_filename"
+
+	[[ -z $fullscreen ]] && {
+		read -r geometry < <(slurp)
+		rec_selection="-g $geometry"
 	}
-	if [[ $microphone = true && $desktop_audio = true ]]
-	then
-	    # this is a temporary solution until wf-recorder has support for recording multiple audio devices
-	    unload_pulse_modules=true
-	    pactl_module_null_sink=$(pactl load-module module-null-sink sink_name=scr_inputs)
-	    pactl_module_loopback1=$(pactl load-module module-loopback sink=scr_inputs)
-	    pactl_module_loopback2=$(pactl load-module module-loopback sink=scr_inputs)
-	    
-	elif [[ $microphone = true ]]
-	then
-	     return 0
-	elif [[ $desktop_audio = true ]]
-	then
-	     return 0
-	fi
+
+	[[ -n $microphone && -n $desktop_audio ]] && {
+		# This is a temporary solution until wf-recorder has support for recording
+		# multiple audio devices.
+		unload_pulse_modules=true
+		pactlm_null_sink=$(pactl load-module module-null-sink sink_name=scr_inputs)
+		pactlm_loopback1=$(pactl load-module module-loopback sink=scr_inputs)
+		pactlm_loopback2=$(pactl load-module module-loopback sink=scr_inputs)
+
+		pactl move-source-output \
+			"$(pactl list source-outputs short | grep lo | tac | awk NR==2'{print $1}')" \
+			"$aud_sink"
+
+		pactl move-source-output \
+			"$(pactl list source-outputs short | grep lo | tac | awk NR==1'{print $1}')" \
+			"$aud_source"
+
+		audio_args="-ascr_inputs.monitor"
+	}
+
+	[[ -n $microphone ]] && audio_args="-a$aud_source"
+	[[ -n $desktop_audio ]] && audio_args="-a$aud_sink"
+	read -ra args <<< "$rec_selection $audio_args"
+
+	wf-recorder "${args[@]}" "$filename" &> "$SCR_CACHE_DIR/rec.log"
+
 	[[ $unload_pulse_modules = true ]] && {
-	    pactl unload-module "$pactl_module_loopback2"
-	    pactl unload-module "$pactl_module_loopback1"
-	    pactl unload-module "$pactl_module_null_sink"
+		pactl unload-module "$pactlm_loopback2"
+		pactl unload-module "$pactlm_loopback1"
+		pactl unload-module "$pactlm_null_sink"
 	}
-    }
-    [[ $XDG_SESSION_TYPE != wayland ]] && { return 1; }
-    echo "$filename"
-    #[[ -z ${microphone_only} ]] && {
-    #	filename="${video_filename}"
-    #	mimetype="${video_mimetype}"
-    #	read -r X Y W H < <(slop -q -f '%x %y %w %h')
-    #	ffmpeg_args="${rec_args} "
-    #	ffmpeg_args+="-s ${W}x${H} -i :0.0+${X},${Y} "
-    #	[[ -n ${audio} ]] && ffmpeg_args+="${rec_audio_args} "
-    #	[[ -n ${microphone} ]] && ffmpeg_args+="${rec_mic_args} "
-    #	[[ -n ${audio} && -n ${microphone} ]] && ffmpeg_args+="${rec_multi_audio_args} "
-    #	ffmpeg_args+="${rec_opt_args} "
-    #
-    #}
-    #
-    #ffmpeg ${ffmpeg_args} ${filename} &> /tmp/scr_rec.log
-    #[[ -n $clipboard ]] && xclip -i -se c -t ${mimetype} ${filename}
+
+	echo "$filename"
 }
 
 $action
diff --git a/root/home/bin/thm b/root/home/bin/thm
--- a/root/home/bin/thm
+++ b/root/home/bin/thm
@@ -1,57 +1,73 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC1090,SC2154
 
-if [[ -n $XDG_CONFIG_HOME ]]
-then
-	thm_config_dir="${XDG_CONFIG_HOME}/thm"
-	thm_dest_dir="${XDG_CONFIG_HOME}/thm/current"
-else
-	thm_config_dir="${HOME}/.config/thm"
-	thm_dest_dir="${HOME}/.config/thm/current"
-fi
+# SC1090 & SC2154
+# The files sourced are user generated files that should contain the needed
+# variables for the script to function correctly. It should be safe to ignore
+# these warnings.
 
-if [[ -z $1 ]]
-then
-	count=0
-	files=("${thm_config_dir}/themes/"*".theme")
-	for f in "${files[@]}"
-	do
-		echo [$count] "${f/${thm_config_dir}\/themes\//}"
-		(( count++ ))
-	done
-	read -rp "Pick a theme: " theme_number
-	. ${files[theme_number]}
-elif [[ ! -f "${thm_config_dir}/themes/${1}.theme" ]]
-then
-	echo "${0##*/}: theme not found"
-	exit 1
-else
-	. "${thm_config_dir}/themes/${1}.theme"
-fi
+usage() {
+	printf '%s\n' "usage: ${0##*/} theme"
+}
 
-bg_color_rgb="$(printf "%d,%d,%d" 0x"${bg_color:0:2}" 0x"${bg_color:2:2}" 0x"${bg_color:4:2}")"
-fg_color_rgb="$(printf "%d,%d,%d" 0x"${fg_color:0:2}" 0x"${fg_color:2:2}" 0x"${fg_color:4:2}")"
-color0_rgb="$(printf "%d,%d,%d" 0x"${color0:0:2}" 0x"${color0:2:2}" 0x"${color0:4:2}")"
-color1_rgb="$(printf "%d,%d,%d" 0x"${color1:0:2}" 0x"${color1:2:2}" 0x"${color1:4:2}")"
-color2_rgb="$(printf "%d,%d,%d" 0x"${color2:0:2}" 0x"${color2:2:2}" 0x"${color2:4:2}")"
-color3_rgb="$(printf "%d,%d,%d" 0x"${color3:0:2}" 0x"${color3:2:2}" 0x"${color3:4:2}")"
-color4_rgb="$(printf "%d,%d,%d" 0x"${color4:0:2}" 0x"${color4:2:2}" 0x"${color4:4:2}")"
-color5_rgb="$(printf "%d,%d,%d" 0x"${color5:0:2}" 0x"${color5:2:2}" 0x"${color5:4:2}")"
-color6_rgb="$(printf "%d,%d,%d" 0x"${color6:0:2}" 0x"${color6:2:2}" 0x"${color6:4:2}")"
-color7_rgb="$(printf "%d,%d,%d" 0x"${color7:0:2}" 0x"${color7:2:2}" 0x"${color7:4:2}")"
-color8_rgb="$(printf "%d,%d,%d" 0x"${color8:0:2}" 0x"${color8:2:2}" 0x"${color8:4:2}")"
-color9_rgb="$(printf "%d,%d,%d" 0x"${color9:0:2}" 0x"${color9:2:2}" 0x"${color9:4:2}")"
-color10_rgb="$(printf "%d,%d,%d" 0x"${color10:0:2}" 0x"${color10:2:2}" 0x"${color10:4:2}")"
-color11_rgb="$(printf "%d,%d,%d" 0x"${color11:0:2}" 0x"${color11:2:2}" 0x"${color11:4:2}")"
-color12_rgb="$(printf "%d,%d,%d" 0x"${color12:0:2}" 0x"${color12:2:2}" 0x"${color12:4:2}")"
-color13_rgb="$(printf "%d,%d,%d" 0x"${color13:0:2}" 0x"${color13:2:2}" 0x"${color13:4:2}")"
-color14_rgb="$(printf "%d,%d,%d" 0x"${color14:0:2}" 0x"${color14:2:2}" 0x"${color14:4:2}")"
-color15_rgb="$(printf "%d,%d,%d" 0x"${color15:0:2}" 0x"${color15:2:2}" 0x"${color15:4:2}")"
+hex2rgb() {
+	hex=$1
+	printf '%d,%d,%d' "0x${hex:0:2}" "0x${hex:2:2}" 0x"${hex:4:2}"
+}
+
+thm_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/thm"
+thm_dest_dir="${XDG_CACHE_HOME:-$HOME/.cache}/thm"
+
+case $1 in
+	-h|--help ) usage; exit 0 ;;
+	"" )
+		count=0
+		files=("$thm_config_dir/themes/"*".theme")
+		for f in "${files[@]}"
+		do
+			f=${f::-6}
+			echo [$count] "${f/$thm_config_dir\/themes\//}"
+			(( count++ ))
+		done
+		read -rp "Pick a theme: " theme_number
+		! [[ $theme_number =~ [0-9]{1,} && $theme_number < $count ]] && \
+			{ echo "${0##*/}: $theme_number: invalid theme number"; exit 1; }
+		. "${files[theme_number]}"
+		;;
+	* )
+		[[ ! -f "${thm_config_dir}/themes/${1}.theme" ]] && \
+			{ echo "${0##*/}: $1: theme not found"; exit 1; }
+		. "${thm_config_dir}/themes/${1}.theme"
+		;;
+esac
+
+bg_color_rgb="$(hex2rgb "$bg_color")"
+fg_color_rgb="$(hex2rgb "$fg_color")"
+color0_rgb="$(hex2rgb "$color0")"
+color1_rgb="$(hex2rgb "$color1")"
+color2_rgb="$(hex2rgb "$color2")"
+color3_rgb="$(hex2rgb "$color3")"
+color4_rgb="$(hex2rgb "$color4")"
+color5_rgb="$(hex2rgb "$color5")"
+color6_rgb="$(hex2rgb "$color6")"
+color7_rgb="$(hex2rgb "$color7")"
+color8_rgb="$(hex2rgb "$color8")"
+color9_rgb="$(hex2rgb "$color9")"
+color10_rgb="$(hex2rgb "$color10")"
+color11_rgb="$(hex2rgb "$color11")"
+color12_rgb="$(hex2rgb "$color12")"
+color13_rgb="$(hex2rgb "$color13")"
+color14_rgb="$(hex2rgb "$color14")"
+color15_rgb="$(hex2rgb "$color15")"
 
 [[ ! -d $thm_dest_dir ]] && {
 	mkdir -p "$thm_dest_dir" || {
-		echo "${0##*/}: couldn't create $thm_dest_dir";exit 1;
+		echo "${0##*/}: couldn't create $thm_dest_dir"; exit 1
 	}
 }
+
+rm "$thm_dest_dir/"*
+
 templates=("${thm_config_dir}/templates/"*"-template")
 for t in "${templates[@]}"
 do
@@ -94,7 +110,7 @@ do
 	file="${file//\{color13.rgb\}/$color13_rgb}"
 	file="${file//\{color14.rgb\}/$color14_rgb}"
 	file="${file//\{color15.rgb\}/$color15_rgb}"
-	printf '%s' "$file" > "${thm_dest_dir}/${file_name}"
+	printf '%s\n' "$file" > "${thm_dest_dir}/${file_name}"
 done
 
 scripts=("${thm_config_dir}/scripts/"*)
diff --git a/root/home/bin/upd b/root/home/bin/upd
--- a/root/home/bin/upd
+++ b/root/home/bin/upd
@@ -1,86 +1,103 @@
 #!/usr/bin/env bash
 
-info() {
-    case $1 in
-	f) msg="fail"; color="\e[31;1m";;
-	i) msg="info"; color="\e[32;1m";;
-	w) msg="warn"; color="\e[33;1m";;
-    esac
-    shift
-    printf "\n${color}%s\e[m %s\n\n" "[${msg}]" "$*"
+usage() {
+	printf '%s\n' "usage: ${0##*/} [options]" \
+	              "options:" \
+	              "  -a: require confirmation to update and remove packages" \
+	              "  -c: remove orphaned packages" \
+	              "  -h: display usage statement" \
+	              "  -l: skip rebuilding live packages" \
+	              "  -r: regenerate ebuild cache" \
+	              "  -s: skip repository sync" \
+	              "  -u: update packages" \
+	              "  -w: wait for intput before continuing"
 }
 
-usage() { printf '%s' "usage: ${0##*/} [options]
-	-a: requires confirmation to update and remove packages
-	-c: removes orphaned packages
-	-h: displays usage statement
-	-r: regenerates ebuild cache
-	-s: skip repository sync
-	-u: updates packages
-"
+info() {
+	case $1 in
+		f) msg="fail"; color="\e[31;1m";;
+		i) msg="info"; color="\e[32;1m";;
+		w) msg="warn"; color="\e[33;1m";;
+	esac
+	shift
+	printf "${color}%s\e[m %s\n" "[${msg}]" "$*"
+}
+
+upd_wait() {
+	[[ -z $upd_wait ]] && return 0
+	while true
+	do
+		read -rp "Continue? [y/n] " input
+		case $input in
+			y ) break ;;
+			n ) info f exiting...; exit 1 ;;
+			* ) info w invalid option: "$input"; continue ;;
+		esac
+	done
 }
 
 remove_orphans() {
-    info i removing orphans
-    command -v emerge &> /dev/null || info w emerge not found
-    printf '%s\n' "$ sudo emerge --depclean --verbose $ask"
-    sudo emerge --depclean --verbose $ask || { info f failed to remove orphans; exit 1; }
-    info i orphans removed
+	info i removing orphans
+	printf '%s\n' "$ sudo emerge --depclean --verbose $ask"
+	sudo emerge --depclean --verbose "$ask" || \
+		{ info f failed to remove orphans; exit 1; }
 }
 
 regen_cache() {
-    info i regenerating ebuild cache
-    command -v emerge &> /dev/null || info w emerge not found
-    printf '%s\n' "$ sudo emerge --regen --verbose"
-    sudo emerge --regen --verbose || { info f failed to regenerate ebuild cache; exit 1; }
-    info i ebuild cache regenerated
+	info i regenerating ebuild cache
+	printf '%s\n' "$ sudo emerge --regen --verbose"
+	sudo emerge --regen --verbose || \
+		{ info f failed to regenerate ebuild cache; exit 1; }
+	upd_wait
 }
 
 sync_repo() {
-    info i syncing repositories
-    command -v emaint &> /dev/null || info w emaint not found
-    printf '%s\n' "$ sudo emaint sync --auto"
-    sudo emaint sync --auto || { info f failed to sync repositories; exit 1;}
-    info i repositories synced
+	info i syncing repositories
+	printf '%s\n' "$ sudo emaint sync --auto"
+	sudo emaint sync --auto || { info f failed to sync repositories; exit 1; }
+	upd_wait
 }
 
 update_pkgs() {
-    info i updating packages
-    command -v emerge &> /dev/null || info w emerge not found
-    printf '%s\n' "$ sudo emerge --update --deep --newuse --changed-deps --with-bdeps=y --verbose @world $ask"
-    sudo emerge --update --deep --changed-deps --newuse --with-bdeps=y --verbose @world $ask || \
-	{ info f failed to update packages; exit 1; }
-    printf '%s\n' "$ sudo emerge --oneshot @live-rebuild $ask"
-    sudo emerge --oneshot @live-rebuild $ask || { info f failed to update live ebuilds; exit 1; }
-    info i packages updated
+	info i updating packages
+	printf '%s' "$ sudo emerge --update --deep --newuse --changed-deps " \
+	            "--with-bdeps=y --verbose @world $ask"
+	sudo emerge --update --deep --changed-deps --newuse --with-bdeps=y --verbose \
+		@world "$ask" || { info f failed to update packages; exit 1; }
+	[[ -n $upd_rebuild_live ]] || {
+		printf '%s\n' "$ sudo emerge --oneshot @live-rebuild $ask"
+		sudo emerge --oneshot @live-rebuild "$ask" || \
+			{ info f failed to rebuild live packages; exit 1; }
+	}
+	upd_wait
 }
 
-upd_sync_repos=true
-upd_regen_cache=false
-upd_update_pkgs=false
-upd_remove_orphans=false
+command -v emerge &> /dev/null || { info f emerge not found; exit 1; }
+command -v emaint &> /dev/null || { info f emaint not found; exit 1; }
 
 [[ -z $* ]] && { sync_repo; exit 0; }
 for (( a=1; a<$(( ${#@} + 1 )); a++ ))
 do
-    arg=${!a}
-    [[ ! $arg =~ ^-.* || ${#arg} -lt 2 ]] && continue
-    for (( i=1; i<${#arg}; i++ ))
-    do
-	case ${arg:$i:1} in
-	    a ) ask="--ask" ;;
-	    c ) upd_remove_orphans=true ;;
-	    h ) usage; exit 0 ;;
-	    r ) upd_regen_cache=true ;;
-	    s ) upd_sync_repos=false ;;
-	    u ) upd_update_pkgs=true ;;
-	    w ) continue ;;
-	    * ) printf '%s\n' "${0##*/}: -${arg:$i:1} is an invalid argument"; usage; exit 1 ;;
-	esac
-    done
+	arg=${!a}
+	[[ ! $arg =~ ^-.* || ${#arg} -lt 2 ]] && continue
+	for (( i=1; i<${#arg}; i++ ))
+	do
+		case ${arg:$i:1} in
+			a ) ask="--ask" ;;
+			c ) upd_del_orphans=0 ;;
+			h ) usage; exit 0 ;;
+			l ) upd_rebuild_live=0 ;;
+			r ) upd_regen_cache=0 ;;
+			s ) upd_skip_sync_repos=1 ;;
+			u ) upd_update_pkgs=0 ;;
+			w ) upd_wait=0 ;;
+			* ) printf '%s\n' "${0##*/}: -${arg:$i:1}: invalid argument"
+			    usage; exit 1 ;;
+		esac
+	done
 done
 
-[[ $upd_sync_repos = true ]] && sync_repo
-[[ $upd_regen_cache = true ]] && regen_cache
-[[ $upd_update_pkgs = true ]] && update_pkgs
-[[ $upd_remove_orphans = true ]] && remove_orphans
+[[ -z $upd_skip_sync_repos ]] && sync_repo
+[[ -n $upd_regen_cache ]] && regen_cache
+[[ -n $upd_update_pkgs ]] && update_pkgs
+[[ -n $upd_del_orphans ]] && remove_orphans
