/shrug

diff --git a/noti/time-date/local-time-date b/noti/time-date/local-time-date
--- a/noti/time-date/local-time-date
+++ b/noti/time-date/local-time-date
@@ -1,26 +1,24 @@
 #!/usr/bin/env sh
 
-# Notification Script to display Local Time & Date
-# Requires:
-#	libnotify or dunstify
-
-app_name="Local Time and Date"
-icon="${HOME}/.dotfiles/global/noti/time-date/icons/local-time-date.png"
+app_name="Time and Date (Local)"
 
 summary="Time: $(date +'%R')"
 body="Date: $(date +'%a %d %b %Y')"
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
-		-i "${icon}" \
 		-r 13596705 \
 		"${summary}" \
 		"${body}"
-else
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
-		-i "${icon}" \
 		"${summary}" \
 		"${body}"
+else
+	echo "dunstify/notify-send not found"
+	exit 1
 fi
diff --git a/noti/time-date/utc-time-date b/noti/time-date/utc-time-date
--- a/noti/time-date/utc-time-date
+++ b/noti/time-date/utc-time-date
@@ -1,26 +1,24 @@
 #!/usr/bin/env sh
 
-# Notification Script to display Time & Date in UTC
-# Requires:
-#	libnotify or dunstify
-
-app_name="UTC Time and Date"
-icon="${HOME}/.dotfiles/global/noti/time-date/icons/utc-time-date.png"
+app_name="Time and Date (UTC)"
 
 summary="Time: $(TZ=UTC date +'%R')"
 body="Date: $(TZ=UTC date +'%a %d %b %Y')"
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
-		-i "${icon}" \
 		-r 13596705 \
 		"${summary}" \
 		"${body}"
-else
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
-		-i "${icon}" \
 		"${summary}" \
 		"${body}"
+else
+	echo "dunstify/notify-send not found"
+	exit 1
 fi
diff --git a/noti/volume/microphone-volume-mute b/noti/volume/microphone-volume-mute
--- a/noti/volume/microphone-volume-mute
+++ b/noti/volume/microphone-volume-mute
@@ -1,24 +1,21 @@
 #!/usr/bin/env sh
 
-# Script to mute volume and display a notification
-# Requires:
-#	libnotify or dunstify
-#	pulseaudio
-
-app_name="Microphone Status"
-summary="Volume Toggle"
+app_name="Microphone"
 
 pactl set-source-mute @DEFAULT_SOURCE@ toggle
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
-		"${summary}" \
-		"Mute: $(pactl list sources | awk NR==9'{print $2}')"
-else
+		"Muted: $(pactl list sources | awk NR==9'{print $2}')"
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
-		"${summary}" \
-		"Mute: $(pactl list sources | awk NR==9'{print $2}')"
+		"Muted: $(pactl list sources | awk NR==9'{print $2}')"
+else
+	echo "dunstify/notify-send not found"
+	exit 1
 fi
diff --git a/noti/volume/speaker-volume-down b/noti/volume/speaker-volume-down
--- a/noti/volume/speaker-volume-down
+++ b/noti/volume/speaker-volume-down
@@ -1,24 +1,24 @@
 #!/usr/bin/env sh
 
-# Script to decrease volume and display a notification
-# Requires:
-#	libnotify or dunstify
-#	pulseaudio
-
-app_name="Speaker Status"
-summary="Volume Down"
+app_name="Speakers"
+summary="Volume: Decreasing"
 
 pactl set-sink-volume @DEFAULT_SINK@ -2%
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
 		"${summary}" \
 		"$(pactl list sinks | awk NR==10'{print $5}')"
-else
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
 		"${summary}" \
 		"$(pactl list sinks | awk NR==10'{print $5}')"
+else
+	echo "dunstify/libnotift not found"
+	exit 1
 fi
diff --git a/noti/volume/speaker-volume-up-all b/noti/volume/speaker-volume-up-all
--- a/noti/volume/speaker-volume-up-all
+++ b/noti/volume/speaker-volume-up-all
@@ -1,26 +1,25 @@
 #!/usr/bin/env sh
 
-# Script to increase volume to 100 and display a notification
-# Requires:
-#	libnotify or dunstify
-#	pulseaudio
-
-app_name="Speaker Status"
-summary="Volume Max"
+app_name="Speakers"
+summary="Volume: Max"
 
 pactl set-sink-volume @DEFAULT_SINK@ 100%
 
-
 sleep .01
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
 		"${summary}" \
 		"$(pactl list sinks | awk NR==10'{print $5}')"
-else
+elif command -v notify-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
 		"${summary}" \
 		"$(pactl list sinks | awk NR==10'{print $5}')"
+else
+	echo "dunstify/notify-send not found"
+	exit 1
 fi
diff --git a/noti/volume/volume-info b/noti/volume/volume-info
--- a/noti/volume/volume-info
+++ b/noti/volume/volume-info
@@ -1,12 +1,6 @@
 #!/usr/bin/env sh
 
-# Script to display information about Volume
-# Requires:
-#	libnotify or dunstify
-#	Pulseaudio
-
-app_name="Volume Status"
-icon="${HOME}/.dotfiles/global/noti/icons/audio.png"
+app_name="Volume Info"
 
 speaker_volume="$(pactl list sinks | awk NR==10'{print $5}')"
 speaker_mute="$(pactl list sinks | awk NR==9'{print $2}')"
@@ -14,27 +8,34 @@ speaker_mute="$(pactl list sinks | awk NR==9'{print $2}')"
 microphone_volume="$(pactl list sources | awk NR==10'{print $5}')"
 microphone_mute="$(pactl list sources | awk NR==9'{print $2}')"
 
-if [ "${speaker_mute}" = 'yes' ]; then
+if [ "${speaker_mute}" = 'yes' ]
+then
 	summary="Speakers: [M] ${speaker_volume}"
 else
 	summary="Speakers: ${speaker_volume}"
 fi
 
-if [ "${microphone_mute}" = 'yes' ];then
+if [ "${microphone_mute}" = 'yes' ]
+then
 	body="Microphone: [M] ${microphone_volume}"
 else
 	body="Microphone: ${microphone_volume}"
 fi
 
-if command -v dunstify; then
+if command -v dunstify
+then
 	dunstify -a "${app_name}" \
 		-t 4000 \
 		-r 13596705 \
 		"${summary}" \
 		"${body}"
-else
+elif command -v notift-send
+then
 	notify-send -t 4000 \
 		-a "${app_name}" \
 		"${summary}" \
 		"${body}"
+else
+	echo "dunstify/notify-send not found"
+	exit 1
 fi
